### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by lghasemzadeh** [czero69/acomoeye-NN#2]
Hello,
In the paper they mentioned that they have created two datasets:
1) a real dataset via an eye tracker device
2) a synthetic dataset
How they generated the second dataset (that infrared synthetic data)? Is it generated by UnityEyes?

Thank you

**Comment by lghasemzadeh** [comment]
Hello,
Is there any update regarding my question? would you please answer?
Thx

**Comment by czero69** [comment]
Hello,

I have no details on how these datasets were generated. For me, even
metadata (how gaze angles are being measured, what do the floats mean
exactly) was not obvious and would need clarification from the Nvidia side,
both for real and rendered datasets.

Best,
KCZ

**Comment by lghasemzadeh** [comment]
Thank you
