### ISSUE TITLE
Dividing NVGaze dataset for training and testing

### ISSUE THREAD

**Issue by rsingh76** [czero69/acomoeye-NN#3]
I am trying to follow this page and write a model in PyTorch. However, I am not sure about how to divide the NVGaze dataset for training/validation/testing. Could you give some insight into how you did it for both real and synthetic datasets?

1. Do you already have the divided txt/csv that I can use?
2. How long does it usually take to train on acomo dataset and NVGaze dataset?
3. I am new to the field and using PyTorch, is there anything I should keep in mind while porting this to PyTorch?

**Comment by czero69** [comment]
Sorry for replaying so late.

1. For AcomoEye train/test split text files are included and a direct comparison can be made. For NVGaze you must create your own split (I want to avoid publishing Nvidia files here). You can follow the way how I did the train/test split.
2. Few hours to one day.
3. I think it should be quite straightforward (and good idea) to implement it in PyTorch
